language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install tox
script:
  - TOX_ENV=`python -c 'import sys; print("py{}{}".format(*sys.version_info))'`
  - VERBOSE=2 tox -e $TOX_ENV
  - if [ $TOX_ENV = "py35" ]; then tox -e docs,flake8; fi
