language: python
python: 3.4
env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=docs
  - TOX_ENV=flake8
  - TOX_ENV=coverage
install:
  - pip install tox
script:
  - VERBOSE=2 tox -e $TOX_ENV
  - if [ $TOX_ENV = "coverage" ]; then pip install coveralls; coveralls; fi
