language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TOX_ENV=coverage VERBOSE=2
matrix:
  include:
    - python: "3.5"
      env: TOX_ENV=docs
    - python: "3.5"
      env: TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
  - if [ $TOX_ENV = "coverage" ]; then pip install coveralls; coveralls; fi
